sudo: false
language: python
python:
  - "2.7"
install:
  - "pip install funcsigs"
  - "pip install pytest pytest-cov"
  - "python setup.py install"
script:
  - "py.test tests --cov=src -vv"
after_success:
  - coveralls