sudo: false
language: python
python:
  - "2.7"
install:
  - "virtualenv e"
  - "source e/bin/activate"
  - "pip install -r dev-requirements.txt"
script:
  - "pytest tests --cov=src -vv"
after_success:
  - coveralls
