sudo: false
language: python
python:
  - "3.7"
  - "3.8"
install:
  - "virtualenv e"
  - "source e/bin/activate"
  - "pip install -r dev-requirements.txt"
before_script: cd src
script:
  - "pytest ../tests --cov=. -vv"
after_success:
  - coveralls
